//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class UITextBean : BaseBean
{
	/// <summary>
	///内容id
	/// </summary>
	public long content;
	[JsonIgnore]
	public string content_language { get => _content_language.Get(() => TextHandler.Instance.GetTextById(UITextCfg.fileName, content)); set => _content_language.Set(value); }
	private LanguageCache _content_language;
	/// <summary>
	///内容
	/// </summary>
	public string remark_content;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class UITextCfg : BaseCfg<long, UITextBean>
{
	public static string fileName = "UIText";
	protected static Dictionary<long, UITextBean> dicData = null;
	public static Dictionary<long, UITextBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static UITextBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static UITextBean GetItemData(long key)
	{
		if (dicData == null)
		{
			UITextBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(UITextBean[] arrayData)
	{
		dicData = new Dictionary<long, UITextBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			UITextBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
